version: '3'
services:
  postgres:
    container_name: devexpobrasil-db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: devexpobrasil
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - docker.env
    networks:
      - postgres


  pgadmin:
    links:
      - postgres:postgres
    container_name: devexpobrasil-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ricardo.sperlongo@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admindevexpo123
    ports:
      - "8080:80"
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - docker.env
    networks:
      - postgres

  redis:
    image: redis
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data:

networks:
  postgres:
    driver: bridge
